// Pools of items players can bid on for each BidOff game mode.
// Real-world rosters (NBA, Premier League, F1) verified via web search
// and user-supplied roster data as of August 2026 (start of the
// 2026-27 NBA/Premier League seasons and the 2026 F1 season). Player
// movement can still happen — spot-check before relying on this as
// ground truth deep into a season.

// Fixed roster composition required per player for game modes that
// draft by position. Game modes not listed here have no position
// requirement — any items from the pool can fill any slot.
const gameSlots = {
  "NBA — Current": { "Centre": 2, "Forward": 4, "Guard": 4 },
  "Premier League — Current": { "Goalkeeper": 1, "Defender": 1, "Midfielder": 2, "Attacker": 1 },
};

const gamePools = {

  "NBA — Current": [
    { name: "Precious Achiuwa", position: "Forward" },
    { name: "Darius Acuff, Jr.", position: "Guard" },
    { name: "Steven Adams", position: "Centre" },
    { name: "Bam Adebayo", position: "Centre" },
    { name: "Michael Ajayi", position: "Forward" },
    { name: "Santi Aldama", position: "Centre" },
    { name: "Trey Alexander", position: "Guard" },
    { name: "Nickeil Alexander-Walker", position: "Guard" },
    { name: "Grayson Allen", position: "Guard" },
    { name: "Jarrett Allen", position: "Centre" },
    { name: "Jose Alvarado", position: "Guard" },
    { name: "Nate Ament", position: "Forward" },
    { name: "Christian Anderson, Jr.", position: "Guard" },
    { name: "Kyle Anderson", position: "Forward" },
    { name: "Giannis Antetokounmpo", position: "Forward" },
    { name: "OG Anunoby", position: "Forward" },
    { name: "Deni Avdija", position: "Guard" },
    { name: "Tobe Awaka", position: "Centre" },
    { name: "Deandre Ayton", position: "Centre" },
    { name: "Marvin Bagley III", position: "Forward" },
    { name: "Ace Bailey", position: "Forward" },
    { name: "LaMelo Ball", position: "Guard" },
    { name: "Mo Bamba", position: "Centre" },
    { name: "Paolo Banchero", position: "Centre" },
    { name: "Desmond Bane", position: "Guard" },
    { name: "Dominick Barlow", position: "Forward" },
    { name: "Harrison Barnes", position: "Forward" },
    { name: "Scottie Barnes", position: "Forward" },
    { name: "Brooks Barnhizer", position: "Forward" },
    { name: "R.J. Barrett", position: "Guard" },
    { name: "Charles Bassey", position: "Forward" },
    { name: "Tamar Bates", position: "Guard" },
    { name: "Jamison Battle", position: "Forward" },
    { name: "Bradley Beal", position: "Guard" },
    { name: "Joan Beringer", position: "Centre" },
    { name: "Saddiq Bey", position: "Forward" },
    { name: "Tarik Biberovic", position: "Guard" },
    { name: "Tyler Bilodeau", position: "Forward" },
    { name: "Goga Bitadze", position: "Centre" },
    { name: "Nate Bittle", position: "Centre" },
    { name: "Anthony Black", position: "Guard" },
    { name: "Bogdan Bogdanovic", position: "Guard" },
    { name: "Adem Bona", position: "Centre" },
    { name: "Devin Booker", position: "Guard" },
    { name: "Cameron Boozer", position: "Forward" },
    { name: "Kylan Boswell", position: "Guard" },
    { name: "Jamaree Bouyea", position: "Guard" },
    { name: "Jaden Bradley", position: "Guard" },
    { name: "Christian Braun", position: "Forward" },
    { name: "Trevon Brazile", position: "Forward" },
    { name: "Koby Brea", position: "Forward" },
    { name: "Mikal Bridges", position: "Guard" },
    { name: "Miles Bridges", position: "Forward" },
    { name: "Dillon Brooks", position: "Forward" },
    { name: "Johni Broome", position: "Centre" },
    { name: "Mikel Brown Jr.", position: "Guard" },
    { name: "Jaylen Brown", position: "Forward" },
    { name: "Kobe Brown", position: "Forward" },
    { name: "Maliq Brown", position: "Forward" },
    { name: "Jalen Brunson", position: "Guard" },
    { name: "Carter Bryant", position: "Forward" },
    { name: "Thomas Bryant", position: "Centre" },
    { name: "Kobe Bufkin", position: "Guard" },
    { name: "Brayden Burries", position: "Forward" },
    { name: "Jimmy Butler III", position: "Forward" },
    { name: "Matas Buzelis", position: "Forward" },
    { name: "Jamal Cain", position: "Forward" },
    { name: "Kentavious Caldwell-Pope", position: "Guard" },
    { name: "Toumani Camara", position: "Forward" },
    { name: "Clint Capela", position: "Forward" },
    { name: "Dylan Cardwell", position: "Forward" },
    { name: "Branden Carlson", position: "Forward" },
    { name: "Cameron Carr", position: "Guard" },
    { name: "Bub Carrington", position: "Guard" },
    { name: "Devin Carter", position: "Guard" },
    { name: "Jevon Carter", position: "Guard" },
    { name: "Wendell Carter, Jr.", position: "Forward" },
    { name: "Alex Caruso", position: "Guard" },
    { name: "Stephon Castle", position: "Guard" },
    { name: "Colin Castleton", position: "Forward" },
    { name: "Chris Cenac, Jr.", position: "Centre" },
    { name: "Julian Champagnie", position: "Forward" },
    { name: "Justin Champagnie", position: "Forward" },
    { name: "Cameron Christie", position: "Guard" },
    { name: "Max Christie", position: "Forward" },
    { name: "Moussa Cisse", position: "Forward" },
    { name: "Sidy Cissoko", position: "Forward" },
    { name: "Jaylen Clark", position: "Guard" },
    { name: "Jordan Clarkson", position: "Guard" },
    { name: "Nicolas Claxton", position: "Centre" },
    { name: "Walter Clayton, Jr.", position: "Guard" },
    { name: "Nique Clifford", position: "Forward" },
    { name: "Donovan Clingan", position: "Centre" },
    { name: "Noah Clowney", position: "Forward" },
    { name: "Isaiah Collier", position: "Guard" },
    { name: "John Collins", position: "Forward" },
    { name: "Zach Collins", position: "Centre" },
    { name: "Mike Conley", position: "Guard" },
    { name: "Pat Connaughton", position: "Forward" },
    { name: "Ryan Conwell", position: "Guard" },
    { name: "Quadir Copeland", position: "Forward" },
    { name: "Bilal Coulibaly", position: "Forward" },
    { name: "Cedric Coward", position: "Forward" },
    { name: "Isaiah Crawford", position: "Forward" },
    { name: "L.J. Cryer", position: "Guard" },
    { name: "Cade Cunningham", position: "Forward" },
    { name: "Stephen Curry", position: "Guard" },
    { name: "Tristan Da Silva", position: "Forward" },
    { name: "Pacome Dadiet", position: "Forward" },
    { name: "Dyson Daniels", position: "Forward" },
    { name: "Anthony Davis", position: "Forward" },
    { name: "Sergio De Larrea", position: "Forward" },
    { name: "Tucker DeVries", position: "Forward" },
    { name: "Egor Demin", position: "Guard" },
    { name: "RayJ Dennis", position: "Guard" },
    { name: "Donte DiVincenzo", position: "Guard" },
    { name: "Malik Dia", position: "Forward" },
    { name: "Moussa Diabate", position: "Forward" },
    { name: "Alpha Diallo", position: "Forward" },
    { name: "Mohamed Diawara", position: "Forward" },
    { name: "Gradey Dick", position: "Forward" },
    { name: "Ousmane Dieng", position: "Guard" },
    { name: "Rob Dillingham", position: "Guard" },
    { name: "Josh Dix", position: "Guard" },
    { name: "Tre Donaldson", position: "Guard" },
    { name: "Luka Doncic", position: "Forward" },
    { name: "Luguentz Dort", position: "Guard" },
    { name: "Ayo Dosunmu", position: "Guard" },
    { name: "Andre Drummond", position: "Centre" },
    { name: "Kris Dunn", position: "Guard" },
    { name: "Ryan Dunn", position: "Guard" },
    { name: "Kevin Durant", position: "Forward" },
    { name: "A.J. Dybantsa", position: "Forward" },
    { name: "Tari Eason", position: "Forward" },
    { name: "Zach Edey", position: "Centre" },
    { name: "V.J. Edgecombe", position: "Forward" },
    { name: "Anthony Edwards", position: "Forward" },
    { name: "Justin Edwards", position: "Forward" },
    { name: "Zuby Ejiofor", position: "Forward" },
    { name: "Keon Ellis", position: "Forward" },
    { name: "Joel Embiid", position: "Centre" },
    { name: "Tristan Enaruna", position: "Forward" },
    { name: "Noa Essengue", position: "Forward" },
    { name: "Isaiah Evans", position: "Guard" },
    { name: "Jeremiah Fears", position: "Guard" },
    { name: "Kyle Filipowski", position: "Centre" },
    { name: "Dorian Finney-Smith", position: "Forward" },
    { name: "Cooper Flagg", position: "Forward" },
    { name: "Adam Flagler", position: "Guard" },
    { name: "Rasheer Fleming", position: "Forward" },
    { name: "Kingston Flemings", position: "Guard" },
    { name: "Simone Fontecchio", position: "Forward" },
    { name: "De'Aaron Fox", position: "Guard" },
    { name: "Enrique Freeman", position: "Forward" },
    { name: "Johnny Furphy", position: "Forward" },
    { name: "Daniel Gafford", position: "Centre" },
    { name: "Myron Gardner", position: "Guard" },
    { name: "Darius Garland", position: "Guard" },
    { name: "Luka Garza", position: "Centre" },
    { name: "Keyonte George", position: "Guard" },
    { name: "Kyshawn George", position: "Forward" },
    { name: "Paul George", position: "Forward" },
    { name: "Taj Gibson", position: "Forward" },
    { name: "Josh Giddey", position: "Guard" },
    { name: "Keshon Gilbert", position: "Guard" },
    { name: "Shai Gilgeous-Alexander", position: "Guard" },
    { name: "Collin Gillespie", position: "Guard" },
    { name: "Ja'Kobi Gillespie", position: "Guard" },
    { name: "Rudy Gobert", position: "Centre" },
    { name: "Vladislav Goldin", position: "Centre" },
    { name: "Hugo Gonzalez", position: "Forward" },
    { name: "Jordan Goodwin", position: "Guard" },
    { name: "Aaron Gordon", position: "Forward" },
    { name: "Jerami Grant", position: "Forward" },
    { name: "Allen Graves", position: "Forward" },
    { name: "A.J. Green", position: "Guard" },
    { name: "Draymond Green", position: "Forward" },
    { name: "Jalen Green", position: "Guard" },
    { name: "Javonte Green", position: "Guard" },
    { name: "Josh Green", position: "Guard" },
    { name: "Quentin Grimes", position: "Guard" },
    { name: "Mouhamed Gueye", position: "Forward" },
    { name: "Rui Hachimura", position: "Forward" },
    { name: "Tyrese Haliburton", position: "Guard" },
    { name: "P.J. Hall", position: "Forward" },
    { name: "Yang Hansen", position: "Centre" },
    { name: "Tim Hardaway Jr.", position: "Guard" },
    { name: "Jaden Hardy", position: "Guard" },
    { name: "E.J. Harkless", position: "Guard" },
    { name: "Dylan Harper", position: "Forward" },
    { name: "Ron Harper, Jr.", position: "Guard" },
    { name: "Gary Harris", position: "Guard" },
    { name: "Tobias Harris", position: "Forward" },
    { name: "Josh Hart", position: "Guard" },
    { name: "Isaiah Hartenstein", position: "Forward" },
    { name: "Sam Hauser", position: "Forward" },
    { name: "Jordan Hawkins", position: "Guard" },
    { name: "Jaxson Hayes", position: "Forward" },
    { name: "Scoot Henderson", position: "Guard" },
    { name: "Taylor Hendricks", position: "Forward" },
    { name: "Chucky Hepburn", position: "Guard" },
    { name: "Tyler Herro", position: "Guard" },
    { name: "Mario Hezonja", position: "Guard" },
    { name: "Buddy Hield", position: "Guard" },
    { name: "Haywood Highsmith", position: "Forward" },
    { name: "Blake Hinson", position: "Guard" },
    { name: "Jrue Holiday", position: "Guard" },
    { name: "Ron Holland", position: "Forward" },
    { name: "DaRon Holmes II", position: "Forward" },
    { name: "Chet Holmgren", position: "Centre" },
    { name: "Al Horford", position: "Centre" },
    { name: "Caleb Houstan", position: "Forward" },
    { name: "Jett Howard", position: "Forward" },
    { name: "Kevin Huerter", position: "Forward" },
    { name: "James Huff", position: "Centre" },
    { name: "Ariel Hukporti", position: "Centre" },
    { name: "De'Andre Hunter", position: "Forward" },
    { name: "C.J. Huntley", position: "Forward" },
    { name: "Bones Hyland", position: "Guard" },
    { name: "Oso Ighodaro", position: "Forward" },
    { name: "Brandon Ingram", position: "Forward" },
    { name: "Harrison Ingram", position: "Forward" },
    { name: "Kyrie Irving", position: "Guard" },
    { name: "Jonathan Isaac", position: "Forward" },
    { name: "G.G. Jackson", position: "Forward" },
    { name: "Isaiah Jackson", position: "Forward" },
    { name: "Andre Jackson, Jr.", position: "Guard" },
    { name: "Jaren Jackson, Jr.", position: "Forward" },
    { name: "Quenton Jackson", position: "Forward" },
    { name: "Trayce Jackson-Davis", position: "Forward" },
    { name: "Kasparas Jakucionis", position: "Guard" },
    { name: "Bronny James", position: "Guard" },
    { name: "LeBron James", position: "Forward" },
    { name: "Sion James", position: "Guard" },
    { name: "Jaime Jaquez, Jr.", position: "Forward" },
    { name: "Joshua Jefferson", position: "Centre" },
    { name: "Trey Jemison", position: "Forward" },
    { name: "Daniss Jenkins", position: "Guard" },
    { name: "Ty Jerome", position: "Guard" },
    { name: "Isaiah Joe", position: "Guard" },
    { name: "A.J. Johnson", position: "Guard" },
    { name: "Cameron Johnson", position: "Guard" },
    { name: "Chaney Johnson", position: "Forward" },
    { name: "Jalen Johnson", position: "Forward" },
    { name: "Morez Johnson, Jr.", position: "Forward" },
    { name: "Keldon Johnson", position: "Forward" },
    { name: "Tre Johnson", position: "Guard" },
    { name: "Nikola Jokic", position: "Centre" },
    { name: "Derrick Jones", position: "Forward" },
    { name: "Herb Jones", position: "Forward" },
    { name: "Isaac Jones", position: "Centre" },
    { name: "Kam Jones", position: "Forward" },
    { name: "Spencer Jones", position: "Forward" },
    { name: "Tre Jones", position: "Guard" },
    { name: "Tyus Jones", position: "Guard" },
    { name: "David Jones-Garcia", position: "Forward" },
    { name: "DeAndre Jordan", position: "Centre" },
    { name: "Nikola Jovic", position: "Forward" },
    { name: "Ryan Kalkbrenner", position: "Centre" },
    { name: "Arthur Kaluma", position: "Forward" },
    { name: "Alex Karaban", position: "Forward" },
    { name: "Yuki Kawamura", position: "Guard" },
    { name: "Luke Kennard", position: "Guard" },
    { name: "Jayson Kent", position: "Guard" },
    { name: "Walker Kessler", position: "Centre" },
    { name: "Corey Kispert", position: "Forward" },
    { name: "Dalton Knecht", position: "Forward" },
    { name: "Kon Knueppel", position: "Forward" },
    { name: "Tyler Kolek", position: "Guard" },
    { name: "Christian Koloko", position: "Centre" },
    { name: "John Konchar", position: "Guard" },
    { name: "Luke Kornet", position: "Forward" },
    { name: "Vit Krejci", position: "Guard" },
    { name: "Kyle Kuzma", position: "Forward" },
    { name: "Jake LaRavia", position: "Forward" },
    { name: "Zach LaVine", position: "Guard" },
    { name: "Jock Landale", position: "Centre" },
    { name: "Chaz Lanier", position: "Guard" },
    { name: "Pelle Larsson", position: "Guard" },
    { name: "Tobi Lawal", position: "Forward" },
    { name: "Caris LeVert", position: "Guard" },
    { name: "Yaxel Lendeborg", position: "Forward" },
    { name: "Kawhi Leonard", position: "Forward" },
    { name: "Malevy Leons", position: "Forward" },
    { name: "Damian Lillard", position: "Guard" },
    { name: "Dereck Lively II", position: "Centre" },
    { name: "Kevon Looney", position: "Forward" },
    { name: "Brook Lopez", position: "Centre" },
    { name: "Karim Lopez", position: "Forward" },
    { name: "Caleb Love", position: "Forward" },
    { name: "Trey Lyles", position: "Forward" },
    { name: "Khaman Maluach", position: "Centre" },
    { name: "Sandro Mamukelashvili", position: "Forward" },
    { name: "Terance Mann", position: "Guard" },
    { name: "Tre Mann", position: "Guard" },
    { name: "Chris Manon", position: "Guard" },
    { name: "Aday Mara", position: "Centre" },
    { name: "Lauri Markkanen", position: "Forward" },
    { name: "Bogoljub Markovic", position: "Forward" },
    { name: "Naji Marshall", position: "Forward" },
    { name: "Alijah Martin", position: "Guard" },
    { name: "Caleb Martin", position: "Forward" },
    { name: "Nick Martinelli", position: "Forward" },
    { name: "Jahmai Mashack", position: "Forward" },
    { name: "Karlo Matkovic", position: "Forward" },
    { name: "Tyrese Maxey", position: "Guard" },
    { name: "Miles McBride", position: "Guard" },
    { name: "Jared McCain", position: "Guard" },
    { name: "C.J. McCollum", position: "Guard" },
    { name: "T.J. McConnell", position: "Guard" },
    { name: "Jaden McDaniels", position: "Forward" },
    { name: "Bryce McGowens", position: "Forward" },
    { name: "Jordan McLaughlin", position: "Guard" },
    { name: "Liam McNeeley", position: "Forward" },
    { name: "De'Anthony Melton", position: "Guard" },
    { name: "Sam Merrill", position: "Guard" },
    { name: "Khris Middleton", position: "Forward" },
    { name: "Duke Miles", position: "Guard" },
    { name: "Baba Miller", position: "Centre" },
    { name: "Brandon Miller", position: "Forward" },
    { name: "Jordan Miller", position: "Guard" },
    { name: "Leonard Miller", position: "Forward" },
    { name: "Riley Minix", position: "Forward" },
    { name: "Josh Minott", position: "Forward" },
    { name: "Yves Missi", position: "Centre" },
    { name: "Ajay Mitchell", position: "Guard" },
    { name: "Davion Mitchell", position: "Guard" },
    { name: "Dillon Mitchell", position: "Forward" },
    { name: "Donovan Mitchell", position: "Guard" },
    { name: "Evan Mobley", position: "Forward" },
    { name: "Jonathan Mogbo", position: "Forward" },
    { name: "Malik Monk", position: "Guard" },
    { name: "Moses Moody", position: "Guard" },
    { name: "Alex Morales", position: "Guard" },
    { name: "Ja Morant", position: "Guard" },
    { name: "Trey Murphy III", position: "Guard" },
    { name: "Dejounte Murray", position: "Guard" },
    { name: "Jamal Murray", position: "Guard" },
    { name: "Keegan Murray", position: "Forward" },
    { name: "Kris Murray", position: "Forward" },
    { name: "Collin Murray-Boyles", position: "Forward" },
    { name: "Svi Mykhailiuk", position: "Forward" },
    { name: "Larry Nance, Jr.", position: "Forward" },
    { name: "Pete Nance", position: "Forward" },
    { name: "Izaiyah Nelson", position: "Centre" },
    { name: "Andrew Nembhard", position: "Guard" },
    { name: "Ryan Nembhard", position: "Guard" },
    { name: "Aaron Nesmith", position: "Forward" },
    { name: "Asa Newell", position: "Forward" },
    { name: "Tristen Newton", position: "Guard" },
    { name: "Yanic Konan Niederhauser", position: "Forward" },
    { name: "Zeke Nnaji", position: "Forward" },
    { name: "Jusuf Nurkic", position: "Centre" },
    { name: "Royce O'Neale", position: "Forward" },
    { name: "AK Okereke", position: "Forward" },
    { name: "Josh Okogie", position: "Guard" },
    { name: "Onyeka Okongwu", position: "Forward" },
    { name: "Ebuka Okorie", position: "Guard" },
    { name: "Isaac Okoro", position: "Guard" },
    { name: "Felix Okpara", position: "Centre" },
    { name: "Ugonna Onyenso", position: "Centre" },
    { name: "Kelly Oubre, Jr.", position: "Forward" },
    { name: "Otega Oweh", position: "Guard" },
    { name: "Gary Payton II", position: "Guard" },
    { name: "Koa Peat", position: "Forward" },
    { name: "Micah Peavy", position: "Forward" },
    { name: "Sean Pedulla", position: "Guard" },
    { name: "Noah Penda", position: "Forward" },
    { name: "Taelon Peter", position: "Guard" },
    { name: "Darryn Peterson", position: "Guard" },
    { name: "Julian Phillips", position: "Forward" },
    { name: "Labaron Philon, Jr.", position: "Guard" },
    { name: "Jalen Pickett", position: "Forward" },
    { name: "Jaron Pierre, Jr.", position: "Forward" },
    { name: "Scotty Pippen, Jr.", position: "Guard" },
    { name: "Daeqwon Plowden", position: "Forward" },
    { name: "Brandin Podziemski", position: "Guard" },
    { name: "Jakob Poeltl", position: "Centre" },
    { name: "Jordan Poole", position: "Guard" },
    { name: "Craig Porter, Jr.", position: "Guard" },
    { name: "Kevin Porter, Jr.", position: "Forward" },
    { name: "Michael Porter, Jr.", position: "Forward" },
    { name: "Bobby Portis", position: "Forward" },
    { name: "Kristaps Porzingis", position: "Centre" },
    { name: "Quinten Post", position: "Centre" },
    { name: "Micah Potter", position: "Centre" },
    { name: "John Poulakidas", position: "Forward" },
    { name: "Drake Powell", position: "Forward" },
    { name: "Norman Powell", position: "Guard" },
    { name: "Taurean Prince", position: "Forward" },
    { name: "Payton Pritchard", position: "Guard" },
    { name: "Tyrese Proctor", position: "Guard" },
    { name: "Olivier-Maxence Prosper", position: "Forward" },
    { name: "Zyon Pullin", position: "Guard" },
    { name: "Jayden Quaintance", position: "Centre" },
    { name: "Derik Queen", position: "Centre" },
    { name: "Neemias Queta", position: "Centre" },
    { name: "Immanuel Quickley", position: "Guard" },
    { name: "Julius Randle", position: "Forward" },
    { name: "Maxime Raynaud", position: "Centre" },
    { name: "Austin Reaves", position: "Guard" },
    { name: "Paul Reed, Jr.", position: "Forward" },
    { name: "Tarris Reed, Jr.", position: "Forward" },
    { name: "Julian Reese", position: "Forward" },
    { name: "Naz Reid", position: "Centre" },
    { name: "Will Richard", position: "Forward" },
    { name: "Jase Richardson", position: "Guard" },
    { name: "Will Riley", position: "Forward" },
    { name: "Zaccharie Risacher", position: "Forward" },
    { name: "Duncan Robinson", position: "Forward" },
    { name: "Mitchell Robinson", position: "Centre" },
    { name: "Ryan Rollins", position: "Guard" },
    { name: "Rayan Rupert", position: "Guard" },
    { name: "D'Angelo Russell", position: "Guard" },
    { name: "Cormac Ryan", position: "Guard" },
    { name: "Domantas Sabonis", position: "Forward" },
    { name: "Tidjane Salaun", position: "Forward" },
    { name: "Kobe Sanders", position: "Forward" },
    { name: "Gui Santos", position: "Forward" },
    { name: "Ben Saraf", position: "Guard" },
    { name: "Alex Sarr", position: "Centre" },
    { name: "Marcus Sasser", position: "Guard" },
    { name: "Baylor Scheierman", position: "Guard" },
    { name: "Dennis Schroder", position: "Guard" },
    { name: "Jaylin Sellers", position: "Guard" },
    { name: "Alperen Sengun", position: "Centre" },
    { name: "Brice Sensabaugh", position: "Forward" },
    { name: "Collin Sexton", position: "Guard" },
    { name: "Landry Shamet", position: "Guard" },
    { name: "Terrence Shannon, Jr.", position: "Forward" },
    { name: "Emanuel Sharp", position: "Guard" },
    { name: "Jamarion Sharp", position: "Centre" },
    { name: "Day'Ron Sharpe", position: "Forward" },
    { name: "Shaedon Sharpe", position: "Forward" },
    { name: "Jamal Shead", position: "Guard" },
    { name: "Ben Sheppard", position: "Guard" },
    { name: "Reed Sheppard", position: "Guard" },
    { name: "Pascal Siakam", position: "Forward" },
    { name: "Anfernee Simons", position: "Guard" },
    { name: "K.J. Simpson", position: "Guard" },
    { name: "Jericho Sims", position: "Centre" },
    { name: "Jalen Slawson", position: "Forward" },
    { name: "Javon Small", position: "Guard" },
    { name: "Marcus Smart", position: "Guard" },
    { name: "Braden Smith", position: "Guard" },
    { name: "Dru Smith", position: "Guard" },
    { name: "Jalen Smith", position: "Centre" },
    { name: "Jabari Smith, Jr.", position: "Forward" },
    { name: "Malachi Smith", position: "Guard" },
    { name: "Tolu Smith", position: "Forward" },
    { name: "Jeremy Sochan", position: "Guard" },
    { name: "Thomas Sorber", position: "Centre" },
    { name: "Cam Spencer", position: "Guard" },
    { name: "Pat Spencer", position: "Guard" },
    { name: "Hannes Steinbach", position: "Forward" },
    { name: "Isaiah Stewart II", position: "Centre" },
    { name: "Bennett Stirtz", position: "Guard" },
    { name: "Julian Strawther", position: "Forward" },
    { name: "Max Strus", position: "Guard" },
    { name: "Jalen Suggs", position: "Guard" },
    { name: "Dailyn Swain", position: "Forward" },
    { name: "Jae'sean Tate", position: "Forward" },
    { name: "Jayson Tatum", position: "Forward" },
    { name: "Adou Thiero", position: "Guard" },
    { name: "Meleek Thomas", position: "Guard" },
    { name: "Amen Thompson", position: "Guard" },
    { name: "Ausar Thompson", position: "Guard" },
    { name: "Klay Thompson", position: "Guard" },
    { name: "Bruce Thornton", position: "Guard" },
    { name: "Matisse Thybulle", position: "Forward" },
    { name: "Nae'qwan Tomlin", position: "Forward" },
    { name: "John Tonje", position: "Forward" },
    { name: "Nikola Topic", position: "Guard" },
    { name: "Obi Toppin", position: "Forward" },
    { name: "Karl-Anthony Towns", position: "Centre" },
    { name: "Nolan Traore", position: "Forward" },
    { name: "Gary Trent, Jr.", position: "Guard" },
    { name: "Oscar Tshiebwe", position: "Forward" },
    { name: "Myles Turner", position: "Centre" },
    { name: "Jaylon Tyson", position: "Forward" },
    { name: "Ernest Udeh, Jr.", position: "Centre" },
    { name: "Milos Uzan", position: "Guard" },
    { name: "Fred VanVleet", position: "Guard" },
    { name: "Jarred Vanderbilt", position: "Forward" },
    { name: "Devin Vassell", position: "Guard" },
    { name: "Henri Veesaar", position: "Centre" },
    { name: "Nikola Vucevic", position: "Forward" },
    { name: "Tristan Vukcevic", position: "Forward" },
    { name: "Dean Wade", position: "Forward" },
    { name: "Keaton Wagler", position: "Guard" },
    { name: "Franz Wagner", position: "Forward" },
    { name: "Moe Wagner", position: "Forward" },
    { name: "Jabari Walker", position: "Forward" },
    { name: "Jarace Walker", position: "Guard" },
    { name: "Cason Wallace", position: "Guard" },
    { name: "Jordan Walsh", position: "Forward" },
    { name: "Ja'Kobe Walter", position: "Forward" },
    { name: "Kel'el Ware", position: "Forward" },
    { name: "P.J. Washington", position: "Forward" },
    { name: "Trendon Watford", position: "Forward" },
    { name: "Jamir Watkins", position: "Forward" },
    { name: "Jaylen Wells", position: "Forward" },
    { name: "Victor Wembanyama", position: "Forward" },
    { name: "Coby White", position: "Guard" },
    { name: "Derrick White", position: "Guard" },
    { name: "Cam Whitmore", position: "Forward" },
    { name: "Aaron Wiggins", position: "Forward" },
    { name: "Andrew Wiggins", position: "Forward" },
    { name: "Amari Williams", position: "Forward" },
    { name: "Cody Williams", position: "Forward" },
    { name: "Grant Williams", position: "Forward" },
    { name: "Jalen Williams", position: "Guard" },
    { name: "Jaylin Williams", position: "Centre" },
    { name: "Kenrich Williams", position: "Forward" },
    { name: "Mark Williams", position: "Centre" },
    { name: "Patrick Williams", position: "Guard" },
    { name: "Robert Williams", position: "Forward" },
    { name: "Ziaire Williams", position: "Forward" },
    { name: "Zion Williamson", position: "Forward" },
    { name: "Caleb Wilson", position: "Forward" },
    { name: "Jalen Wilson", position: "Forward" },
    { name: "Danny Wolf", position: "Centre" },
    { name: "Trae Young", position: "Guard" },
    { name: "Chris Youngblood", position: "Guard" },
    { name: "Rocco Zikarsky", position: "Centre" },
    { name: "Ivica Zubac", position: "Centre" },
  ],

  "Premier League — Current": [
    { name: "Erling Haaland", position: "Attacker" },
    { name: "Bukayo Saka", position: "Attacker" },
    { name: "Cole Palmer", position: "Midfielder" },
    { name: "Declan Rice", position: "Midfielder" },
    { name: "Alexander Isak", position: "Attacker" },
    { name: "Bruno Fernandes", position: "Midfielder" },
    { name: "Virgil van Dijk", position: "Defender" },
    { name: "Phil Foden", position: "Midfielder" },
    { name: "Martin Ødegaard", position: "Midfielder" },
    { name: "Ollie Watkins", position: "Attacker" },
    { name: "James Maddison", position: "Midfielder" },
    { name: "Nicolas Jackson", position: "Attacker" },
    { name: "Moises Caicedo", position: "Midfielder" },
    { name: "William Saliba", position: "Defender" },
    { name: "Jarrod Bowen", position: "Attacker" },
    { name: "Gabriel Martinelli", position: "Attacker" },
    { name: "Kai Havertz", position: "Attacker" },
    { name: "Morgan Rogers", position: "Midfielder" },
    { name: "Jean-Philippe Mateta", position: "Attacker" },
    { name: "Ismaïla Sarr", position: "Attacker" },
    { name: "Jeremy Doku", position: "Attacker" },
    { name: "João Pedro", position: "Attacker" },
    { name: "Enzo Fernández", position: "Midfielder" },
    { name: "Rayan Cherki", position: "Midfielder" },
    { name: "David Raya", position: "Goalkeeper" },
    { name: "Antoine Semenyo", position: "Attacker" },
    { name: "Florian Wirtz", position: "Midfielder" },
    { name: "Bruno Guimarães", position: "Midfielder" },
    { name: "Illan Meslier", position: "Goalkeeper" },
    { name: "Christos Tzolis", position: "Attacker" },
    { name: "Piero Hincapié", position: "Defender" },
    { name: "Ronald Araújo", position: "Defender" },
    { name: "Emiliano Martínez", position: "Goalkeeper" },
    { name: "Dean Henderson", position: "Goalkeeper" },
    { name: "Caoimhín Kelleher", position: "Goalkeeper" },
    { name: "Robin Roefs", position: "Goalkeeper" },
    { name: "Senne Lammens", position: "Goalkeeper" },
    { name: "Ruben Dias", position: "Defender" },
    { name: "Gabriel Magalhães", position: "Defender" },
    { name: "Josko Gvardiol", position: "Defender" },
    { name: "Marc Guéhi", position: "Defender" },
    { name: "Marcos Senesi", position: "Defender" },
    { name: "James Tarkowski", position: "Defender" },
    { name: "Tyrick Mitchell", position: "Defender" },
    { name: "Nico O'Reilly", position: "Defender" },
    { name: "Conor Bradley", position: "Defender" },
    { name: "Andrew Robertson", position: "Defender" },
    { name: "Alexis Mac Allister", position: "Midfielder" },
    { name: "Youri Tielemans", position: "Midfielder" },
    { name: "Ryan Gravenberch", position: "Midfielder" },
    { name: "Mohammed Kudus", position: "Midfielder" },
  ],

  "F1 — Current": [
    "Max Verstappen",
    "Isack Hadjar",
    "Lando Norris",
    "Oscar Piastri",
    "Charles Leclerc",
    "Lewis Hamilton",
    "George Russell",
    "Kimi Antonelli",
    "Carlos Sainz",
    "Alexander Albon",
    "Fernando Alonso",
    "Lance Stroll",
    "Pierre Gasly",
    "Franco Colapinto",
    "Esteban Ocon",
    "Oliver Bearman",
    "Liam Lawson",
    "Arvid Lindblad",
    "Nico Hülkenberg",
    "Gabriel Bortoleto",
    "Sergio Pérez",
    "Valtteri Bottas",
  ],

  "Marvel — Build a Squad": [
    "Iron Man",
    "Captain America",
    "Thor",
    "Black Widow",
    "Hulk",
    "Hawkeye",
    "Spider-Man",
    "Doctor Strange",
    "Black Panther",
    "Captain Marvel",
    "Scarlet Witch",
    "Vision",
    "Ant-Man",
    "Wasp",
    "Star-Lord",
    "Gamora",
    "Rocket Raccoon",
    "Groot",
    "Winter Soldier",
    "Falcon",
    "Loki",
    "Nick Fury",
    "Wolverine",
    "Deadpool",
    "Shang-Chi",
    "Ms. Marvel",
    "Daredevil",
    "Moon Knight",
    "Nova",
    "Iron Fist",
    "Luke Cage",
    "She-Hulk",
    "Silver Surfer",
    "Cyclops",
    "Storm",
    "Jean Grey",
    "Professor X",
    "Beast",
    "Nightcrawler",
    "Colossus",
    "Rogue",
    "Punisher",
    "Blade",
    "Cable",
    "Squirrel Girl",
    "Ghost Rider",
    "Elektra",
    "Jessica Jones",
    "Kate Bishop",
    "America Chavez",
    "Adam Warlock",
    "Mantis",
    "Drax",
    "Nebula",
  ],

};
