// Pools of items players can bid on for each BidOff game mode.
// Real-world rosters (NBA, Premier League, F1) verified via web search
// as of August 2026 (start of the 2026-27 NBA/Premier League seasons
// and the 2026 F1 season). Player movement can still happen — spot-check
// before relying on this as ground truth deep into a season.

const gamePools = {

  "NBA — Current": [
    "Nikola Jokić",
    "Luka Dončić",
    "Giannis Antetokounmpo",
    "Shai Gilgeous-Alexander",
    "Jayson Tatum",
    "Anthony Edwards",
    "Victor Wembanyama",
    "Joel Embiid",
    "Kevin Durant",
    "Stephen Curry",
    "LeBron James",
    "Damian Lillard",
    "Devin Booker",
    "Tyrese Haliburton",
    "Donovan Mitchell",
    "Jalen Brunson",
    "Ja Morant",
    "Zion Williamson",
    "Paolo Banchero",
    "Anthony Davis",
    "Kawhi Leonard",
    "Paul George",
    "Jimmy Butler",
    "James Harden",
    "Karl-Anthony Towns",
    "Domantas Sabonis",
    "Trae Young",
    "De'Aaron Fox",
    "Bam Adebayo",
    "Jaylen Brown",
    "Deandre Ayton",
    "Julius Randle",
    "Rudy Gobert",
    "Chet Holmgren",
    "Scottie Barnes",
    "Cade Cunningham",
    "Franz Wagner",
    "Alperen Şengün",
    "Jaren Jackson Jr.",
    "Kristaps Porziņģis",
    "Brandon Ingram",
    "Zach LaVine",
    "DeMar DeRozan",
    "Fred VanVleet",
    "Jrue Holiday",
    "Draymond Green",
    "Klay Thompson",
    "Kyrie Irving",
    "CJ McCollum",
    "Lauri Markkanen",
    "Desmond Bane",
    "Tyler Herro",
    "Coby White",
    "Josh Giddey",
    "Evan Mobley",
    "Darius Garland",
    "Jalen Williams",
    "Amen Thompson",
    "LaMelo Ball",
    "Isaiah Hartenstein",
  ],

  "Premier League — Current": [
    "Erling Haaland",
    "Bukayo Saka",
    "Cole Palmer",
    "Declan Rice",
    "Alexander Isak",
    "Bruno Fernandes",
    "Virgil van Dijk",
    "Phil Foden",
    "Martin Ødegaard",
    "Ollie Watkins",
    "James Maddison",
    "Nicolas Jackson",
    "Moises Caicedo",
    "William Saliba",
    "Jarrod Bowen",
    "Gabriel Martinelli",
    "Kai Havertz",
    "Morgan Rogers",
    "Jean-Philippe Mateta",
    "Ismaïla Sarr",
    "Jeremy Doku",
    "João Pedro",
    "Enzo Fernández",
    "Rayan Cherki",
    "David Raya",
    "Antoine Semenyo",
    "Florian Wirtz",
    "Bruno Guimarães",
    "Illan Meslier",
    "Christos Tzolis",
    "Piero Hincapié",
    "Ronald Araújo",
  ],

  "F1 — Current": [
    "Max Verstappen",
    "Isack Hadjar",
    "Lando Norris",
    "Oscar Piastri",
    "Charles Leclerc",
    "Lewis Hamilton",
    "George Russell",
    "Kimi Antonelli",
    "Carlos Sainz",
    "Alexander Albon",
    "Fernando Alonso",
    "Lance Stroll",
    "Pierre Gasly",
    "Franco Colapinto",
    "Esteban Ocon",
    "Oliver Bearman",
    "Liam Lawson",
    "Arvid Lindblad",
    "Nico Hülkenberg",
    "Gabriel Bortoleto",
    "Sergio Pérez",
    "Valtteri Bottas",
  ],

  "Marvel — Build a Squad": [
    "Iron Man",
    "Captain America",
    "Thor",
    "Black Widow",
    "Hulk",
    "Hawkeye",
    "Spider-Man",
    "Doctor Strange",
    "Black Panther",
    "Captain Marvel",
    "Scarlet Witch",
    "Vision",
    "Ant-Man",
    "Wasp",
    "Star-Lord",
    "Gamora",
    "Rocket Raccoon",
    "Groot",
    "Winter Soldier",
    "Falcon",
    "Loki",
    "Nick Fury",
    "Wolverine",
    "Deadpool",
    "Shang-Chi",
    "Ms. Marvel",
    "Daredevil",
    "Moon Knight",
    "Nova",
    "Iron Fist",
    "Luke Cage",
    "She-Hulk",
    "Silver Surfer",
    "Cyclops",
    "Storm",
    "Jean Grey",
    "Professor X",
    "Beast",
    "Nightcrawler",
    "Colossus",
    "Rogue",
    "Punisher",
    "Blade",
    "Cable",
    "Squirrel Girl",
    "Ghost Rider",
    "Elektra",
    "Jessica Jones",
    "Kate Bishop",
    "America Chavez",
    "Adam Warlock",
    "Mantis",
    "Drax",
    "Nebula",
  ],

};
