// Pools of items players can bid on for each BidOff game mode.
// Real-world rosters (NBA, Premier League, F1) reflect knowledge as of
// early 2026 and should be spot-checked for any moves since then.

const gamePools = {

  "NBA — Current": [
    "Nikola Jokić",
    "Luka Dončić",
    "Giannis Antetokounmpo",
    "Shai Gilgeous-Alexander",
    "Jayson Tatum",
    "Anthony Edwards",
    "Victor Wembanyama",
    "Joel Embiid",
    "Kevin Durant",
    "Stephen Curry",
    "LeBron James",
    "Damian Lillard",
    "Devin Booker",
    "Tyrese Haliburton",
    "Donovan Mitchell",
    "Jalen Brunson",
    "Ja Morant",
    "Zion Williamson",
    "Paolo Banchero",
    "Anthony Davis",
    "Kawhi Leonard",
    "Paul George",
    "Jimmy Butler",
    "James Harden",
    "Karl-Anthony Towns",
    "Domantas Sabonis",
    "Trae Young",
    "De'Aaron Fox",
    "Bam Adebayo",
    "Jaylen Brown",
  ],

  "Premier League — Current": [
    "Erling Haaland",
    "Bukayo Saka",
    "Cole Palmer",
    "Declan Rice",
    "Alexander Isak",
    "Bruno Fernandes",
    "Virgil van Dijk",
    "Phil Foden",
    "Martin Ødegaard",
    "Rodri",
    "Ollie Watkins",
    "James Maddison",
    "Nicolas Jackson",
    "Moises Caicedo",
    "William Saliba",
    "Jarrod Bowen",
    "Gabriel Martinelli",
    "Kai Havertz",
    "Morgan Rogers",
    "Jean-Philippe Mateta",
  ],

  "F1 — Current": [
    "Max Verstappen",
    "Lando Norris",
    "Oscar Piastri",
    "Charles Leclerc",
    "Lewis Hamilton",
    "George Russell",
    "Kimi Antonelli",
    "Carlos Sainz",
    "Fernando Alonso",
    "Lance Stroll",
    "Pierre Gasly",
    "Esteban Ocon",
    "Yuki Tsunoda",
    "Liam Lawson",
    "Alexander Albon",
    "Nico Hülkenberg",
    "Oliver Bearman",
    "Gabriel Bortoleto",
    "Isack Hadjar",
    "Franco Colapinto",
  ],

  "Marvel — Build a Squad": [
    "Iron Man",
    "Captain America",
    "Thor",
    "Black Widow",
    "Hulk",
    "Hawkeye",
    "Spider-Man",
    "Doctor Strange",
    "Black Panther",
    "Captain Marvel",
    "Scarlet Witch",
    "Vision",
    "Ant-Man",
    "Wasp",
    "Star-Lord",
    "Gamora",
    "Rocket Raccoon",
    "Groot",
    "Winter Soldier",
    "Falcon",
    "Loki",
    "Nick Fury",
    "Wolverine",
    "Deadpool",
    "Shang-Chi",
    "Ms. Marvel",
    "Daredevil",
    "Moon Knight",
    "Nova",
  ],

};
